### ISSUE TITLE
无法提交到git仓库

### ISSUE THREAD

**Issue by flyrainning** [hooray/fantastic-startkit#3]
我的项目git仓库是在`/home/rain/Desktop/test`目录，然后在仓库中建立目录v1/manager，在这个manager目录中使用了fantastic-startkit（从https://gitee.com/hooray/fantastic-startkit.git 中clone然后复制粘贴过来），也就是说fantastic-startkit的package.json位置是在`/home/rain/Desktop/test/v1/manager/package.json`

当我根据文档，将package.json中 `"postinstall": "simple-git-hooks"` 修改成 `"postinstall": "cd ../.. && simple-git-hooks"` 后，执行pnpm install报错
```
[ERROR], Was not able to set git hooks. Error: Error: ENOENT: no such file or directory, stat '/home/rain/Desktop/test/package.json'
```
将package.json文件修改回 `"postinstall": "simple-git-hooks"`，执行pnpm install正常通过。提示
```
[INFO] Successfully set the pre-commit with command: pnpm lint-staged
[INFO] Successfully set all git hooks
```

但是当我执行git commit提交时，产生了下面的错误提示，无法提交
```
ERR_PNPM_NO_IMPORTER_MANIFEST_FOUND  No package.json (or package.yaml, or package.json5) was found in "/home/rain/Desktop/test".
```

请问要怎样才能正常commit，谢谢

**Comment by hooray** [comment]
你需要在 `package.json` 中修改 `pre-commit` 的 hook
```
  "simple-git-hooks": {
    "pre-commit": "cd v1/master/ && pnpm lint-staged",
    "preserveUnused": true
  }
```
然后重新安装依赖后，应该可以正常提交。

另外最好再重新下一份最新的源码（gitee是隔天自动同步，所以从github上下载是最新的），我刚修改了点模板里文件缺失的bug

**Comment by flyrainning** [comment]
修改`package.json`后解决问题，谢谢
